openapi: 3.0.3
info:
  title: Gokabam API
  description: defines the logic structure for the Gokabam hexbatch token and delivery service
  version: 1.0.0
  termsOfService: 'https://api.hexbatch.com/v1/service'
  contact:
    email: development@hexbatch.com
    url: 'https://api.hexbatch.com/v1/contact'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: 'https://api.hexbatch.com/v1'
    description: Used to show and test this api

security:
  - BasicAuth: []
tags:
  - name: boundary
    description: token types have boundaries in space and time
  - name: tokenType
    description: Each token has at least one type
    externalDocs:
      description: Find out more
      url: https://api.hexbatch.com/v1/token_types
  - name: token
    description: What is managed here. Tokens have one or more token types
    externalDocs:
      description: Find out more
      url: https://api.hexbatch.com/v1/tokens

paths: {}
components:
  securitySchemes:
    # Basic authentication
    BasicAuth:
      type: http
      scheme: basic