openapi: 3.0.3
info:
  title: Hexbatch boundary management
  description: Creates, manages boundaries for attributes
  version: 1.0.0
  termsOfService: 'https://api.hexbatch.com/v1/docs/service'
  contact:
    email: development@hexbatch.com
    url: 'https://api.hexbatch.com/v1/docs/contact'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: 'https://api.hexbatch.com/v1/users'
    description: Used to show and test this api

security:
  - BasicAuth: []
tags:
  - name: users
    description: Users have to be logged in to do most api operations
    externalDocs:
      description: Find out more
      url: https://api.hexbatch.com/v1/docs/core/users
  - name: user_groups
    description: Permissions in the api is defined by the groups the user belongs
    externalDocs:
      description: Find out more
      url: https://api.hexbatch.com/v1/docs/core/user_groups

paths: {}
components:
  schemas: {}
  securitySchemes:
    # Basic authentication
    BasicAuth:
      type: http
      scheme: basic