openapi: 3.0.3
info:
  title: Hexbatch scripts management
  description: Creates, manages, tests the action scripts
  version: 1.0.0
  termsOfService: 'https://api.hexbatch.com/v1/service'
  contact:
    email: development@hexbatch.com
    url: 'https://api.hexbatch.com/v1/contact'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: 'https://api.hexbatch.com/v1/actions'
    description: Used to show and test this api

security:
  - BasicAuth: []
tags:
  - name: action
    description: this holds a script to be run
    externalDocs:
      description: Find out more
      url: https://api.hexbatch.com/v1/docs/core/actions

paths: {}
components:
  schemas: {}
  securitySchemes:
    # Basic authentication
    BasicAuth:
      type: http
      scheme: basic