openapi: 3.0.3
info:
  title: Hexbatch attributes management
  description: Creates, manages attributes
  version: 1.0.0
  termsOfService: 'https://api.hexbatch.com/v1/service'
  contact:
    email: development@hexbatch.com
    url: 'https://api.hexbatch.com/v1/contact'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: 'https://api.hexbatch.com/v1/attributes'
    description: Used to show and test this api

security:
  - BasicAuth: []

tags: []

paths: {}
components:
  schemas: {}
  securitySchemes:
    # Basic authentication
    BasicAuth:
      type: http
      scheme: basic