openapi: 3.0.3
info:
  title: Hexbatch boundary management
  description: Creates, manages boundaries for attributes
  version: 1.0.0
  termsOfService: 'https://api.hexbatch.com/v1/docs/service'
  contact:
    email: development@hexbatch.com
    url: 'https://api.hexbatch.com/v1/docs/contact'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: 'https://api.hexbatch.com/v1/bounds'
    description: Used to show and test this api

security:
  - BasicAuth: []
tags:
  - name: location_bounds
    description: This boundary is defined by an area on a map
    externalDocs:
      description: Find out more
      url: https://api.hexbatch.com/v1/docs/location_bounds
  - name: time_bounds
    description: This boundary is defined by a slice of time
    externalDocs:
      description: Find out more
      url: https://api.hexbatch.com/v1/docs/time_bounds

paths: {}
components:
  schemas: {}
  securitySchemes:
    # Basic authentication
    BasicAuth:
      type: http
      scheme: basic